apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring-app
    spec:
      containers:
          - name: spring-app
            image: "app:1.4"
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080