apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-spring-app
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080